### ISSUE TITLE
replace selected image with cropped image before upload

### ISSUE THREAD

**Issue by snake-venom-nk** [shabuninil/fileup#5]
@shabuninil I want to embed an image cropping to all images before upload images on the server.
Would it be possible to replace the selected image with a cropped image?

**Comment by n2ref** [comment]
The image that is displayed in the img tag before loading is displayed in the data url format.

https://developer.mozilla.org/ru/docs/Web/HTTP/Basics_of_HTTP/Data_URIs

If you find a suitable editor that can handle such formats, then you can crop the image, and then send it to the server, but I'm not sure that such web editors exist. Most likely, you can just mark the coordinates on the image, transfer these coordinates to the server along with the original image, and crop the image at these coordinates on the server.

**Comment by snake-venom-nk** [comment]
@shabuninil  thank you for your answer, i tried to replace the image base64 value with my "cropped" image 

**When I selected the image :**
`<div class="fileup-preview"><img alt="image_2021.png" src="original-image-base64" /></div>`

**replaced with cropped image base64**
`<div class="fileup-preview"><img alt="image_2021.png" src="cropped image base64" /> </div>`

and then hit the upload button, but still I can check "original-image-base64" is save in my folder but not the cropped image. 

I want to know, is there any way to replace the image content with the cropped images before uploading on the server?

As I can read your script is uploading data from "inputID" , so if I want to replace the cropped image with the selected one then something we need to change with this "inputID"  ..

**Comment by n2ref** [comment]
You say everything is correct, for some reason I did not take this into account. The plugin loads the files contained in the input tag, not the img tag. You cannot influence the content of the tag input in any way, since the browser cannot do it.

At the moment, the solution to this problem may be to use the OnBeforeStart event and change the contents of the file in it. I'm not completely sure of the success of this idea.

`onBeforeStart (xhr, file_number, file)`
After calling this event, the file will be sent to `xhr.send(file)` to the server.

https://developer.mozilla.org/en-US/docs/Web/API/File

I would lean towards transferring the file as is and slicing it on the server.
